# DockerComposeのバージョン
version: '3.8'
# サービスの名前[app / web / db]
services:
  db:
    build:
      context: ./docker/db
    container_name: db
    volumes: 
    - db-data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: devroot
      MYSQL_DATABASE: devapp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 3306:3306
  app:
    build: ./docker/app
    container_name: app
    command: php-fpm -F
    volumes:
      - ./src:/var/www/html
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
  web:
    build:
      context: ./docker/web
    container_name: web
    volumes:
    - ./src:/var/www/html
    - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8081:80"
    links:
      - app

volumes:
  db-data:

